/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EventCardComponent: typeof import('./src/assets/vue/components/EventCardComponent/EventCardComponent.vue')['default']
    FooterComponent: typeof import('./src/assets/vue/components/FooterComponent/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/assets/vue/components/HeaderComponent/HeaderComponent.vue')['default']
    MenuComponent: typeof import('./src/assets/vue/components/MenuComponent/MenuComponent.vue')['default']
    ModalComponent: typeof import('./src/assets/vue/components/ModalComponent/ModalComponent.vue')['default']
    NotificationComponent: typeof import('./src/assets/vue/components/NotificationComponent/NotificationComponent.vue')['default']
    ParticipantListComponent: typeof import('./src/assets/vue/components/ParticipantListComponent/ParticipantListComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagComponent: typeof import('./src/assets/vue/components/TagComponent/TagComponent.vue')['default']
  }
}
